server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


spring:
  application:
    name: apigateway-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/users/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/hello
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id : api-server
          uri: lb://API-SERVER
          predicates:
            - Path=/shop/hello
          filters:
            - RemoveRequestHeader=Cookie


jwt:
  secret: super-strong-secret-key-that-is-256-bits-long!