server:
  port: 8000
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    non-secure-port: ${server.port}
    instance-id: GATEWAY-SERVICE-${server.port}



management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

spring:
  application:
    name: apigateway-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-server
          uri: lb://API-SERVER
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/hell
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: api-server
          uri: lb://API-SERVER
          predicates:
            - Path=/api/shop/hello
          filters:
            - RemoveRequestHeader=Cookie
        - id: api-server
          uri: lb://API-SERVER
          predicates:
            - Path=/api/shop/**,/api/admin/**




jwt:
  secret: super-strong-secret-key-that-is-256-bits-long!