server:
  port: 8000
  shutdown: graceful

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /management

spring:
  application:
    name: apigateway-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/users/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/hello
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id : api-server
          uri: lb://API-SERVER
          predicates:
            - Path=/shop/hello
          filters:
            - RemoveRequestHeader=Cookie




jwt:
  secret: super-strong-secret-key-that-is-256-bits-long!